### ISSUE TITLE
MQTT client error

### ISSUE THREAD

**Issue by meinscheins** [meinscheins/gr-electrosense#1]
When trying the example MQTT client test the following error occurs upon sending an command:

```
Generating: '/home/michi/work/electrosense_mqtt_test.py'

Executing: /usr/bin/python3 -u /home/michi/work/electrosense_mqtt_test.py

Connected with result code 0
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/michi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3452, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/home/michi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/home/michi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "/home/michi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "/home/michi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "/home/michi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2936, in _packet_handle
    return self._handle_publish()
  File "/home/michi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3216, in _handle_publish
    self._handle_on_message(message)
  File "/home/michi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3444, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "/usr/lib/python3.9/site-packages/electrosense/mqtt_client.py", line 62, in on_message
    data = msg.payload.split(",")
TypeError: a bytes-like object is required, not 'str'
```

https://stackoverflow.com/questions/42612002/python-sockets-error-typeerror-a-bytes-like-object-is-required-not-str-with/42612820 seems to be problem on how python 3 handles the transmission of strings.

**Comment by meinscheins** [comment]
After converting msg.payload to a string we obtain the following error
```
Executing: /usr/bin/python3 -u /home/michi/work/electrosense_mqtt_test.py

Connected with result code 0
<class 'bytes'>
handler caught exception: pmt_length: wrong_type : (rfgain . 10)
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/gnuradio/gr/gateway.py", line 78, in eval
    try: self._callback(arg)
  File "/usr/lib/python3.9/site-packages/electrosense/variable_updater.py", line 49, in handle_msg
    msg = pmt.to_python(msg_pmt)
  File "/usr/lib/python3.9/site-packages/pmt/pmt_to_python.py", line 126, in pmt_to_python
    return to_python(p)
  File "/usr/lib/python3.9/site-packages/pmt/pmt_to_python.py", line 57, in pmt_to_dict
    for i in range(pmt.length(items)):
  File "/usr/lib/python3.9/site-packages/pmt/pmt_swig.py", line 2439, in length
    return _pmt_swig.length(v)
RuntimeError: pmt_length: wrong_type : (rfgain . 10)
thread[thread-per-block[11]: <block variable_updater(5)>]: SWIG director method error. Error detected when calling 'feval_p.eval'
```

**Comment by meinscheins** [comment]
After fixing the MQTT Client problem the following way.
```
def on_message(self, client, userdata, msg):
        data = msg.payload.split(",".encode())
        data[0]=data[0].decode('ascii')
        data[1]=data[1].decode('ascii')
        self.message_port_pub(pmt.intern('out'), pmt.cons(pmt.intern(data[0]), pmt.intern(data[1])))`
```
We encounter a new problem with the variable updater.
```
Connected with result code 0
(rfgain . 10)
<class 'pmt.pmt_swig.swig_pmt_ptr'>
handler caught exception: pmt_length: wrong_type : (rfgain . 10)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gnuradio/gr/gateway.py", line 78, in eval
    try: self._callback(arg)
  File "/usr/local/lib/python3/dist-packages/electrosense/variable_updater.py", line 51, in handle_msg
    msg = pmt.to_python(msg_pmt)
  File "/usr/lib/python3/dist-packages/pmt/pmt_to_python.py", line 126, in pmt_to_python
    return to_python(p)
  File "/usr/lib/python3/dist-packages/pmt/pmt_to_python.py", line 57, in pmt_to_dict
    for i in range(pmt.length(items)):
  File "/usr/lib/python3/dist-packages/pmt/pmt_swig.py", line 2647, in length
    return _pmt_swig.length(v)
RuntimeError: pmt_length: wrong_type : (rfgain . 10)
thread[thread-per-block[12]: <block variable_updater(5)>]: SWIG director method error. Error detected when calling 'feval_p.eval'

```

**Comment by meinscheins** [comment]
It seems to be a problem with how SWIG handles polymorphic types and how it changed between Python 2.7 and Python 3.
Type of msg_pmt in variable_updater.py in GR 3.7
```
(rfgain . 10)
<class 'pmt.pmt_swig.swig_int_ptr'>
```
in GR 3.8
```
(rfgain . 10)
<class 'pmt.pmt_swig.swig_pmt_ptr'>
```
